CREATE TABLE Obecnosc(
course_id VARCHAR(10) NOT NULL,
data VARCHAR(10) NOT NULL,
student_id INT(6) NOT NULL,
FOREIGN KEY (student_id) REFERENCES Student(id)
ON DELETE CASCADE)
ENGINE=INNODB
DEFAULT CHARACTER SET = utf8;
